baseURL = ""
languageCode = "en-us"
title = "测试站点"
theme = "meteor"
paginate = 9
hasCJKLanguage = true
summaryLength = 100

[markup]
  [markup.tableOfContents]  # 文章目录
    endLevel = 3
    ordered = false
  [markup.highlight]
    style ="github"    # 高亮风格
    lineNos = false         # 是否显示行号
  [markup.goldmark]         # 是否在md文件中渲染html代码
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "不如吃茶去"
  logo = "https://img.zburu.com/author1.png"
  author = "子舒"
  favicon = "https://img.zburu.com/favicon.png"
  buildDate = "2020-06-14"
  beian = "浙ICP备2022002453号-2"
  styleModule = "1"   # 0 or 1 两种不同风格样式

[permalinks]
  blog = "/posts/:title.html/"

